CREATE TABLE property_lotus_x (
    PROPERTY_ID INT NOT NULL AUTO_INCREMENT,
    HOTEL_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	COUNTRY_CODE VARCHAR(255) NOT NULL,
	STATE_CODE VARCHAR(255) NOT NULL,
	DESTINATION_CODE VARCHAR(255) NOT NULL,
	ZONE_CODE VARCHAR(255) NOT NULL,
	LONGITUDE VARCHAR(255) NOT NULL,
	LATITUDE VARCHAR(255) NOT NULL,
	CATEGORY_CODE VARCHAR(255) NOT NULL,
	CATEGORY_GROUP_CODE VARCHAR(255) NOT NULL,
	ACCOMMODATION_TYPE_CODE VARCHAR(255) NOT NULL,
	SEGMENT_CODES VARCHAR(255) NOT NULL, 
	ADDRESS VARCHAR(255) NOT NULL,
	POSTAL_CODE VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LICENSE VARCHAR(255) NOT NULL,
	PHONES VARCHAR(255) NOT NULL,
	WEB VARCHAR(255) NOT NULL,
	LAST_UPDATE VARCHAR(255) NOT NULL,
	RANKING VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE TABLE rooms_lotus_x (
	ROOMS_ID INT NOT NULL AUTO_INCREMENT,
	HOTEL_ID VARCHAR(255) NOT NULL,
	ROOM_CODE VARCHAR(255) NOT NULL,
	ROOM_TYPE VARCHAR(255) NOT NULL,
	CHARACTERISTIC_CODE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(ROOMS_ID)
);

CREATE TABLE facilities_lotus_x (
	FACILITIES_ID INT NOT NULL AUTO_INCREMENT,
	HOTEL_ID VARCHAR(255) NOT NULL,
	FACILITY_CODE VARCHAR(255) NOT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	FACILITY_NUMBER VARCHAR(255) NOT NULL,
	VOUCHER VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(FACILITIES_ID)
);

CREATE TABLE terminals_lotus_x (
    TERMINALS_ID INT NOT NULL AUTO_INCREMENT,
    HOTEL_ID VARCHAR(255) NOT NULL,
	TERMINAL_CODE VARCHAR(255) NOT NULL,
	DISTANCE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(TERMINALS_ID)
);

CREATE TABLE interest_points_lotus_x (
    INTEREST_POINTS_ID INT NOT NULL AUTO_INCREMENT,
    HOTEL_ID VARCHAR(255) NOT NULL,
	FACILITY_CODE VARCHAR(255) NOT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	POI_NAME VARCHAR(255) NOT NULL,
	DISTANCE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(INTEREST_POINTS_ID)
);

CREATE TABLE images_lotus_x (
	IMAGES_ID INT NOT NULL AUTO_INCREMENT,
	HOTEL_ID VARCHAR(255) NOT NULL,
	IMAGE_TYPE_CODE VARCHAR(255) NOT NULL,
	IMAGE_PATH VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	VISUAL_ORDER VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(IMAGES_ID)
);