CREATE TABLE property_lotus_x (
    PROPERTY_ID INT NOT NULL AUTO_INCREMENT,
    HOTELID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	COUNTRYCODE VARCHAR(255) NOT NULL,
	STATECODE VARCHAR(255) NOT NULL,
	DESTINATIONCODE VARCHAR(255) NOT NULL,
	ZONECODE VARCHAR(255) NOT NULL,
	LONGITUDE VARCHAR(255) NOT NULL,
	LATITUDE VARCHAR(255) NOT NULL,
	CATEGORYCODE VARCHAR(255) NOT NULL,
	CATEGORYGROUPCODE VARCHAR(255) NOT NULL,
	ACCOMMODATIONTYPECODE VARCHAR(255) NOT NULL,
	SEGMENTCODESVARCHAR(255) NOT NULL, 
	ADDRESS VARCHAR(255) NOT NULL,
	POSTALCODE VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LICENSE VARCHAR(255) NOT NULL,
	PHONES VARCHAR(255) NOT NULL,
	WEB VARCHAR(255) NOT NULL,
	LASTUPDATE VARCHAR(255) NOT NULL,
	RANKING VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE TABLE rooms_lotus_x (
	ROOMS_ID INT NOT NULL AUTO_INCREMENT,
	HOTELID VARCHAR(255) NOT NULL,
	ROOMCODE VARCHAR(255) NOT NULL,
	ROOMTYPE VARCHAR(255) NOT NULL,
	CHARACTERISTICCODE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(ROOMS_ID)
);

CREATE TABLE facilities_lotus_x (
	FACILITIES_ID INT NOT NULL AUTO_INCREMENT,
	HOTELID VARCHAR(255) NOT NULL,
	FACILITYCODE VARCHAR(255) NOT NULL,
	FACILITYGROUPCODE VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	FACILITY_NUMBER VARCHAR(255) NOT NULL,
	VOUCHER VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(FACILITIES_ID)
);

CREATE TABLE terminals_lotus_x (
    TERMINALS_ID INT NOT NULL AUTO_INCREMENT,
    HOTELID VARCHAR(255) NOT NULL,
	TERMINALCODE VARCHAR(255) NOT NULL,
	DISTANCE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(TERMINALS_ID)
);

CREATE TABLE interest_Points_lotus_x (
    INTEREST_POINTS_ID INT NOT NULL AUTO_INCREMENT,
    HOTELID VARCHAR(255) NOT NULL,
	FACILITYCODE VARCHAR(255) NOT NULL,
	FACILITYGROUPCODE VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	POINAME VARCHAR(255) NOT NULL,
	DISTANCE VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(INTEREST_POINTS_ID)
);

CREATE TABLE images_lotus_x (
	IMAGES_ID INT NOT NULL AUTO_INCREMENT,
	HOTELID VARCHAR(255) NOT NULL,
	IMAGETYPECODE VARCHAR(255) NOT NULL,
	IMAGE_PATH VARCHAR(255) NOT NULL,
	ORDER VARCHAR(255) NOT NULL,
	VISUALORDER VARCHAR(255) NOT NULL,
	CONTRACT_TYPE VARCHAR(255) NOT NULL,
	PRIMARY KEY(IMAGES_ID)
);