CREATE TABLE IF NOT EXISTS `property_lotus_x` (
    PROPERTY_ID INT NOT NULL AUTO_INCREMENT,
    HOTEL_ID INT(11) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	COUNTRY_CODE VARCHAR(255) DEFAULT NULL,
	STATE_CODE VARCHAR(255) DEFAULT NULL,
	DESTINATION_CODE VARCHAR(255) DEFAULT NULL,
	ZONE_CODE VARCHAR(255) DEFAULT NULL,
	LONGITUDE VARCHAR(255) DEFAULT NULL,
	LATITUDE VARCHAR(255) DEFAULT NULL,
	CATEGORY_CODE VARCHAR(255) DEFAULT NULL,
	CATEGORY_GROUP_CODE VARCHAR(255) DEFAULT NULL,
	ACCOMMODATION_TYPE_CODE VARCHAR(255) DEFAULT NULL,
	SEGMENT_CODES VARCHAR(255) DEFAULT NULL, 
	ADDRESS VARCHAR(255) DEFAULT NULL,
	POSTAL_CODE VARCHAR(255) DEFAULT NULL,
	CITY VARCHAR(255) DEFAULT NULL,
	EMAIL VARCHAR(255) DEFAULT NULL,
	LICENSE VARCHAR(255) DEFAULT NULL,
	PHONES VARCHAR(255) DEFAULT NULL,
	WEB VARCHAR(255) DEFAULT NULL,
	LAST_UPDATE VARCHAR(255) DEFAULT NULL,
	RANKING VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE TABLE IF NOT EXISTS `rooms_lotus_x` (
	ROOMS_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	ROOM_CODE VARCHAR(255) DEFAULT NULL,
	ROOM_TYPE VARCHAR(255) DEFAULT NULL,
	CHARACTERISTIC_CODE VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ROOMS_ID)
);

CREATE TABLE IF NOT EXISTS `facilities_lotus_x` (
	FACILITIES_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	FACILITY_CODE VARCHAR(255) DEFAULT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) DEFAULT NULL,
	ORDER VARCHAR(255) DEFAULT NULL,
	FACILITY_NUMBER VARCHAR(255) DEFAULT NULL,
	VOUCHER VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(FACILITIES_ID)
);

CREATE TABLE IF NOT EXISTS `terminals_lotus_x` (
    TERMINALS_ID INT DEFAULT NULL AUTO_INCREMENT,
    HOTEL_ID INT(11) DEFAULT NULL,
	TERMINAL_CODE VARCHAR(255) DEFAULT NULL,
	DISTANCE VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(TERMINALS_ID)
);

CREATE TABLE IF NOT EXISTS `interest_points_lotus_x` (
    INTEREST_POINTS_ID INT DEFAULT NULL AUTO_INCREMENT,
    HOTEL_ID INT(11) DEFAULT NULL,
	FACILITY_CODE VARCHAR(255) DEFAULT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) DEFAULT NULL,
	ORDER VARCHAR(255) DEFAULT NULL,
	POI_NAME VARCHAR(255) DEFAULT NULL,
	DISTANCE VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(INTEREST_POINTS_ID)
);

CREATE TABLE IF NOT EXISTS `images_lotus_x` (
	IMAGES_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	IMAGE_TYPE_CODE VARCHAR(255) DEFAULT NULL,
	IMAGE_PATH VARCHAR(255) DEFAULT NULL,
	ORDER VARCHAR(255) DEFAULT NULL,
	VISUAL_ORDER VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(IMAGES_ID)
);

CREATE TABLE IF NOT EXISTS `room_facilities_lotus_x` (
	ROOM_FACILITIES_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	FACILITY_CODE VARCHAR(255) DEFAULT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) DEFAULT NULL,
	IND_YES_OR_NO VARCHAR(255) DEFAULT NULL,
	VOUCHER VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ROOM_FACILITIES_ID)
);

CREATE TABLE IF NOT EXISTS `room_stays_lotus_x` (
	ROOM_STAYS_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	STAY_TYPE VARCHAR(255) DEFAULT NULL,
	ORDER VARCHAR(255) DEFAULT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ROOM_STAYS_ID)
);

CREATE TABLE IF NOT EXISTS `room_stay_facilities_lotus_x` (
	ROOM_STAY_FACILITIES_ID INT DEFAULT NULL AUTO_INCREMENT,
	HOTEL_ID INT(11) DEFAULT NULL,
	FACILITY_CODE VARCHAR(255) DEFAULT NULL,
	FACILITY_GROUP_CODE VARCHAR(255) DEFAULT NULL,
	FACILITY_NUMBER VARCHAR(255) DEFAULT NULL,
	CONTRACT_TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(ROOM_STAY_FACILITIES_ID)
);
